spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wms3?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: ymj1329

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.wms.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    devtools:
      restart:
        enabled: true
        additional-paths: src/main
        exclude: static/**
    map-underscore-to-camel-case: true
server:
  port: 8008


